### ISSUE TITLE
Execute command

### ISSUE THREAD

**Issue by krosoftware** [mikeduglas/libcurl#1]
Hello Mike
is there any example how to execute SSH command on remote server, for example:
sudo service apache2 restart

Thank you.

**Comment by mikeduglas** [comment]
Hi,

maybe there is, I don't know. Try this page:
https://curl.haxx.se/libcurl/c/example.html.

Mike

2017-12-19 17:33 GMT+03:00 krosoftware <notifications@github.com>:

**Comment by krosoftware** [comment]
Thank you.

**Comment by mikeduglas** [comment]
closed due to inactive for long time.
