### ISSUE TITLE
Clarion 6.3 FormPost example doesn´t work

### ISSUE THREAD

**Issue by kcirtapsi** [mikeduglas/libcurl#2]
Hi, 
I have the Clarion 6.3 version and after to follow the instructions from homepage i can see Clarion imported the libcurl to the system.

But after to create a window and a button, and put code above in the button source area it doesn´t work, specially the line about to include the .inc file

`
PRAGMA('project(#compile libcurl.clw)')
  PRAGMA('project(#pragma link(libcurl.lib))')

  INCLUDE('libcurl.inc')
`

Someone could help me with that ?

**Comment by mikeduglas** [comment]
Can't find the instructions which told you to add these lines:
PRAGMA('project(#compile libcurl.clw)')
PRAGMA('project(#pragma link(libcurl.lib))')

If you use libcurl global template, the line
INCLUDE('libcurl.inc')
also not required.

**Comment by mikeduglas** [comment]
of course, if you for some reason can't use the template, these lines can be added manually:
```
PRAGMA('project(#pragma link(libcurl.lib))')
INCLUDE('libcurl.inc')
```
But be sure to select correct embed point - "Before global includes" is OK.

**Comment by kcirtapsi** [comment]
I'm sorry Mike
The case is that I'm just trying to solve a problem on Clarion, but I don't program on it, everything is new. 

I registered libcur as the main page shows, and now I just wanna use it functions in a button source, so after to register I don't need to use those lines I wrote and I can use directly the functions?

Thanks

**Comment by mikeduglas** [comment]
Ah ok, I understood now what you're trying to do. Well, FormPost.clw is source module, which includes some instructions not required in APPs. What you need to do is:

1. Go to Global embeds, locate "Before global INCLUDEs" point and add there 
`PRAGMA('project(#pragma link(libcurl.lib))')  `
`INCLUDE('libcurl.inc') `
2. In your window procedure under button's Accepted event add following call:
`DO CallLibcurl`
3. In Procedure Routines embed point add this CallLibcurl routine (paset data into DATA section, code into CODE section):
```
CallLibcurl  ROUTINE
  DATA
curl                          TCurlHttpClass
res                           CURLcode
cfres                         CURLFormcode
respfile                      STRING(256)
  CODE
  curl.Init()
  !-- add form field
  cfres = curl.FormAdd('comment', 'test')
  IF cfres <> CURL_FORMADD_OK
    MESSAGE('FormAdd failed: '& curl.StrFormAddError(cfres), 'FormPost test', ICON:Asterisk)
    RETURN
  END
  !-- add file
  cfres = curl.FormAddFile('userfile', 'test.xml')
  IF cfres <> CURL_FORMADD_OK
    MESSAGE('FormAddFile failed: '& curl.StrFormAddError(cfres), 'FormPost test', ICON:Asterisk)
    RETURN
  END
  respfile = 'FormPost_response.txt'
  res = curl.FormPost('http://127.0.0.1/index.php', respfile)
  IF res = CURLE_OK
    MESSAGE('Success, see file '& CLIP(respfile) &' for details', 'FormPost test', ICON:Asterisk)
  ELSIF res = -1
    MESSAGE('FormPost failed: errcode '& res, 'FormPost test', ICON:Asterisk)
  ELSE
    MESSAGE('FormPost failed: '& curl.StrError(res), 'FormPost test', ICON:Exclamation)
  END
```

**Comment by kcirtapsi** [comment]
Thanks a lot man, I'll try it soon as possible!

**Comment by kcirtapsi** [comment]
Thanks a lot @mikeduglas , it worked very well, with this example i created another POST codes for my needs, thanks a lot for your help !!
