### ISSUE TITLE
curl file upload in clarion 6.3

### ISSUE THREAD

**Issue by djole-bigbyte** [mikeduglas/libcurl#4]
Hi Mike,

I have to upload somefile.xml to somewebservice using libcurl system. 

The original request is:

curl -X POST “https://somewebservice/api/publicApi/sales-invoice/ubl/upload?requestId=200719791&sendToCir=No" -H “accept: text/plain” -H “ApiKey: 33b67551-973e-4f4b-93f0-f9b251d5b51d” -H “Content-Type: multipart/form-data” -F “ublFile=@somefile.xml;type=text/xml”

I don't have username and password. I have ApiKey instead.

My last Clarion 6.3 routine for this is:

SendDoc ROUTINE
   DATA
curl       TCurlHttpClass
res        CURLcode
cfres      CURLFormcode
respBuffer &IDynStr

respfile   STRING(260)

DelPos     SHORT
FileDir    STRING(260)
i LONG

   CODE

   respfile = 'Response.txt'
   bGetServerResponse  = True
   FileDir = '\\Desktop'

   SSLInfo:bUseSSL     = True
   SSLInfo:bVerifyHost = True
   SSLInfo:bVerifyPeer = False
   SSLInfo:Certificate = '.\certificates\mycert.crt'
   SSLInfo:Version     = CURL_SSLVERSION_DEFAULT

   !-X POST “https://somewebservice/api/publicApi/sales-invoice/ubl/upload?requestId=200719791&sendToCir=No" 
   Send:Url = 'https://somewebservice/api/publicApi/sales-invoice/ubl/upload?requestId=200719791&sendToCir=No'

   !-H “accept: text/plain” -H “ApiKey: 33b67551-973e-4f4b-93f0-f9b251d5b51d” -H “Content-Type: multipart/form-data”
   HttpHeaders.HttpHeader = 'accept: text/plain'; ADD(HttpHeaders)
   HttpHeaders.HttpHeader = 'ApiKey: 33b67551-973e-4f4b-93f0-f9b251d5b51d'; ADD(HttpHeaders)
   HttpHeaders.HttpHeader = 'Content-Type: multipart/form-data'; ADD(HttpHeaders)

   !-F “ublFile=@somefile.xml;type=text/xml”

   respBuffer &= NewDynStr()
   curl.Init()

!*** Headers *********************************************************************************
   curl.FreeHttpHeaders()
   IF RECORDS(HttpHeaders)
      LOOP i = 1 TO RECORDS(HttpHeaders)
         GET(HttpHeaders, i)
         curl.AddHttpHeader(HttpHeaders.HttpHeader)
         IF res <> CURLE_OK
            MESSAGE('AddHttpHeader failed: '& curl.StrError(res), 'libcurl', ICON:Exclamation)
            GOTO Kraj
         END
      END
      res = curl.SetHttpHeaders()
      IF res <> CURLE_OK
         MESSAGE('SetHttpHeaders failed: '& curl.StrError(res), 'libcurl', ICON:Exclamation)
         GOTO Kraj
      END
   END

!*** SSL *****************************************************************************************
   res = curl.SetSSLVerifyHost(SSLInfo:bVerifyHost)
   IF res <> CURLE_OK
      MESSAGE('SetSSLVerifyHost failed: '& curl.StrError(res), 'libcurl', ICON:Exclamation)
      GOTO Kraj
   END
   res = curl.SetSSLVerifyPeer(SSLInfo:bVerifyPeer)
   IF res <> CURLE_OK
      MESSAGE('SetSSLVerifyPeer failed: '& curl.StrError(res), 'libcurl', ICON:Exclamation)
      GOTO Kraj
   END
   res = curl.SetSSLVersion(SSLInfo:Version)
   IF res <> CURLE_OK
      MESSAGE('SetSSLVersion failed: '& curl.StrError(res), 'libcurl', ICON:Exclamation)
      GOTO Kraj
   END
   IF LEN(CLIP(SSLInfo:Certificate))
      res = curl.SetCAInfo(SSLInfo:Certificate)
      IF res <> CURLE_OK
         MESSAGE('SetCAInfo failed: '& curl.StrError(res), 'libcurl', ICON:Exclamation)
         GOTO Kraj
      END
   END

   SETPATH(FileDir)

   IF NOT EXISTS(CLIP(Send:FileName)) ! somefile.xml
      MESSAGE(CLIP(Send:FileName)&' not found, Path: '&PATH())
      GOTO Kraj
   END

!*** Sending *** here is the problem !!!    !-F "ublFile=@somefile.xml;type=text/xml"
   !-- add form field            application/xml text/xml
   cfres = curl.FormAdd('type', 'text/xml')
   IF cfres <> CURL_FORMADD_OK
      MESSAGE('FormAdd failed: '& curl.StrFormAddError(cfres), 'FormPost test', ICON:Asterisk)
      GOTO Kraj
   END

   !-- add file
!   cfres = curl.FormAddFile('ublfile', 'ublfile=@'& CLIP(Send:FileName) &';type=text/xml') ! - Doesn't work
   cfres = curl.FormAddFile('ublfile',  CLIP(Send:FileName)) ! - This works but badly
   IF cfres <> CURL_FORMADD_OK
      MESSAGE('FormAddFile failed: '& curl.StrFormAddError(cfres), 'FormPost test', ICON:Asterisk)
      GOTO Kraj
   END

!*** SendRequest ************************************************************************
   res = curl.FormPost(CLIP(Send:Url), respfile)
   IF res = CURLE_OK

 The result is Ok, but allways I get the response like:
<html>
   <head>
      <title>Error</title>
   </head>
   <body>
      <h2>ERROR: </h2>
      <br>
   </body>
</html>

Something with !-- add form field or !-- add file is wrong.
I have this opinion because this is only difference in comparison to other requests instead of file uploding that I do, and are Ok.

   ELSIF res = -1
      txtHttpResponse = 'FormPost failed: errcode '& res
      MESSAGE('FormPost failed: errcode '& res, 'FormPost test', ICON:Asterisk)

   ELSE
      txtHttpResponse = 'FormPost failed: '& curl.StrError(res)
      MESSAGE('FormPost failed: '& curl.StrError(res), 'FormPost test', ICON:Exclamation)

   END

Kraj
   DisposeDynStr(respBuffer)

   SETPATH(SavPath)
   DISPLAY

Please help me to resolve this

Thank you in advance,
George

**Comment by mikeduglas** [comment]
Hi @djole-bigbyte 
Looks like you should use this:
`cfres = curl.FormAddFile('ublfile', Send:FileName, 'text/xml')`

and remove this call completely:
`cfres = curl.FormAdd('type', 'text/xml')`

Note: libcurl docs suggest to use mime posts instead of multipart/form-data (the methods FormAdd, FormAddFile), see MimePost.clw example.

**Comment by djole-bigbyte** [comment]
Thank you Mike a milion. It works very good.The reason that I didn"t reply earlier is testing the new code. Thank you againGeorge 2. 3. 2023. 14:36, Mike ***@***.***> је написао/ла:
Hi @djole-bigbyte
Looks like you should use this:
cfres = curl.FormAddFile('ublfile', Send:FileName, 'text/xml')
and remove this call completely:
cfres = curl.FormAdd('type', 'text/xml')
Note: libcurl docs suggest to use mime posts instead of multipart/form-data (the methods FormAdd, FormAddFile), see MimePost.clw example.

**Comment by mikeduglas** [comment]
Glad you resolved it!
